### PR TITLE
Overhaul large OD tool to resolve various problems (second attempt)

### PR DESCRIPTION
**Pull request by mmorang**
Full overhaul of tool. Fixes a couple of key things:
- Pipes logger messages to GP UI, including regular status updates (https://github.com/Esri/large-network-analysis-tools/issues/7)
- Better handles time and distance units and pre-selecting based on straight-line distance
- Puts OD settings in a config file for easy access
- Ensures proper post-processing to handle finding the closest K destinations so that when all chunks are stitched back together, the top K are kept.
- Add unit tests to ensure correctness
- Convert from tbx to pyt

My first attempt at an overhaul is in https://github.com/Esri/large-network-analysis-tools/pull/8. I realized upon more detailed testing of that overhaul that the tool would fail with a schema lock error if the user used map layers as barriers. This led me to redesign and refactor everything again, which is in this new pull request. Additional improvements in this version include:
- Ability to use map layers successfully for all inputs
- Support for selection sets and definition queries on the input origins and destinations

From a technical standpoint, here is what this PR does compared to the previous attempt:
- Preprocessing and input validation is done on the main execution thread rather than in the subprocess. This avoids the schema lock problem and allows us to use selections and definition queries on the inputs since they are preprocessed before being passed to the subprocess via their catalog paths
- Cleaner class-based structure for validation, pre-processing, and post-processing

There is one bit of weirdness happening in unittests_tool.py. Something about the combination of the unittest framework and .pyt script tools is causing errors when the script tool calls arcpy.CheckOutExtension("network"). I cannot reproduce a problem outside the test framework, and the tests pass if I comment out arcpy.CheckOutExtension("network"), so I've decided to ignore this odd problem.

### CODE REVIEW

**Comment by mmorang** [comment]
Found another issue. When using AGOL (and presumably any service) as the network data source, the output OriginOID and DestinationOID fields do not match the input data. They seem to be reset to start at 1 and be consecutive, thereby losing the information about the actual OIDs used in the chunk being analyzed. The output merged results have meaningles OriginOID and DestinationOID values.

I think this is actually a bug either in the services or in the Pro code that handles the services results. However, we will need to work around it in this tool since we want to get this tool working in a shorter timeframe than we can fix the main issue.

**Comment by mmorang** [comment]
Fixed the aforementioned issue with not properly transferring OriginOID and DestinationOID for services solves using a workaround in the tool code.

**Review by deelesh — APPROVED** [review]
@mmorang 
This looks good. Some minor comments
- We should ideally name the py files containing the tests within the unittest folder to be `test_<something>.py`. That way the tests can be run by other test runners such as the runner provided by the pytest framework
- I see the `solve_od_in_parallel` is always creating multiple worker process even when the entire OD can be solved in a single chunk. While this is not a big issue since the primary purpose of this tool is to solve large ODs which will need multiple chunks, it will speed up execution for smaller OD (that can be solved in one chunk) if the tool does not use concurrent.futures at all when the entire solve can be done in one chunk.

**Comment by mmorang** [comment]
Updated the test file names.

Regarding the other thing - this is overall a very inefficient way to solve a small OD for more reasons than just that, so I'm going to leave it for now.

Woohoo, I think we're done!

**Pull request merged**
